controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# config/routes.yaml

admin_dashboard:
  path: /admin/dashboard
  controller: App\Controller\Admin\DashboardControllerAdmin::index

employe_dashboard:
  path: /employe/dashboard
  controller: App\Controller\Admin\DashboardControllerEmploye::index

